version: "3.2"
services:
  ui-api:
    build: '../blackcreek-api/blackcreek-api_service/ui-service/'
    restart: always
    networks:
      - backend
      - ui-api
    volumes:
      - ../blackcreek-api/blackcreek-api_service/ui-service/xproject/:/var/www/html/
    ports:
      - "8082:80"
    links:
      - blackcreek_db

  admin-api:
     build: "../blackcreek-api/blackcreek-api_service/admin-service/"
     restart: always
     networks:
       - backend
       - admin-api
     volumes:
       - ../blackcreek-api/blackcreek-api_service/admin-service/xproject/:/var/www/html/
     ports:
       - "8083:80"
     links:
       - blackcreek_db

  admin-service:
          build: "../blackcreek_admin_service/"
          restart: always
          volumes: 
              - ../blackcreek_admin_service/:/code
          ports:
              - "8080:8000"
          networks:
               - backend
                
  data_provider_client:
          build: "../blackcreek-data_provider_client/"
          restart: always
          volumes:
             - ../blackcreek-data_provider_client/:/code
          ports:
              - "8081:8000"
          networks:
              - backend

  api-doc:
     build: "../blackcreek-api/blackcreek-api_service/apidoc-service/"
     restart: always
     volumes:
       - ../blackcreek-api/blackcreek-api_service/apidoc-service/doc/:/usr/share/nginx/html/
       - ../blackcreek-api/blackcreek-api_service/apidoc-service/doc/:/var/www/html/
     networks:
       - doc
     ports:
       - "8090:90"

  admin_db:
     image: mysql:5.6.40
     networks: 
       - admin-api
     environment:
       - MYSQL_ROOT_PASSWORD=xproject
       - MYSQL_DATABASE=xproject

  static_file_handler:
          build: "../blackcreek_static_file_handler/"
          restart: always
          volumes:
                - ../blackcreek_static_file_handler/web/:/usr/share/nginx/html/
                - ../blackcreek_static_file_handler/web/:/var/www/html/
          ports:
               - "8091:90"
          networks:
              - backend

  blackcreek_db:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=xproject
      - MYSQL_DATABASE=xproject
networks:
  backend:
  ui-api:
  admin-api:
  doc:

